### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [peterservice-rnd/robotframework-couchbaselibrary#8]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 2.0.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary robotframework-couchbaselibrary -w /tmp/ext robotframework-couchbaselibrary==2.0.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting robotframework-couchbaselibrary==2.0.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/659/19984fe762c0a/robotframework-couchbaselibrary-2.0.1.tar.gz (4.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-hnv77rhq/robotframework-couchbaselibrary/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-hnv77rhq/robotframework-couchbaselibrary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-hnv77rhq/robotframework-couchbaselibrary/pip-egg-info
         cwd: /tmp/pip-wheel-hnv77rhq/robotframework-couchbaselibrary/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-hnv77rhq/robotframework-couchbaselibrary/setup.py", line 14, in <module>
        with open(path.join(here, 'requirements.txt')) as f:
      File "/usr/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-hnv77rhq/robotframework-couchbaselibrary/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
It gets further in the build process now, but I don't have libcouchbase to really test.

**Comment by nixuewei** [comment]
same issue

**Comment by nixuewei** [comment]
ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-3kc4a480/robotframework-couchbaselibrary/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-3kc4a480/robotframework-couchbaselibrary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-install-3kc4a480/robotframework-couchbaselibrary/pip-egg-info
         cwd: /private/tmp/pip-install-3kc4a480/robotframework-couchbaselibrary/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-3kc4a480/robotframework-couchbaselibrary/setup.py", line 14, in <module>
        with open(path.join(here, 'requirements.txt')) as f:
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 904, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/pip-install-3kc4a480/robotframework-couchbaselibrary/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
